- name: Simple Rulebook for Demo
  hosts: all
  sources:
    - name: Demo Source
      ansible.eda.generic:
        payload:
          - msg: "Welcome"
          - msg: "Adios"
  rules:
    - name: Say Hello
      condition: event.msg == "Welcome"
      action:
        debug:
          msg: "Hello from EDA"
