---
- name: EDA Hackathon Rulebook
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Ansible message
      condition: event.payload.message == "Ansible is super cool"
      action:
        debug:
